"""
Persistencia en Oracle Database.

Schema normalizado: contenidos → clasificaciones → categorias + terminos_clave.
Driver: python-oracledb (thin mode siempre — soporta wallets mTLS nativamente).
Thick mode (Oracle Instant Client) habilitable solo si se necesita.
Funciona con FreeSQL.com, Docker, y OCI Autonomous Database.
"""

from collections import defaultdict
from typing import Any

import oracledb

from .config import settings


def get_connection() -> oracledb.Connection:
    """Devuelve una conexión a Oracle Database.

    - Si hay wallet configurada → thin mode con wallet mTLS
    - Si no → thin mode directo (FreeSQL.com, Docker, ADB sin wallet)
    """
    if settings.oracle_wallet_dir:
        # Modo thin con wallet mTLS (no requiere Oracle Instant Client).
        # python-oracledb 2.0+ soporta wallets en thin mode de forma nativa.
        # TODO: si en el futuro se necesita thick mode (pools heterogéneos,
        #       NNE, Kerberos, SODA), agregar acá:
        #   oracledb.init_oracle_client(lib_dir=r"ruta\al\instantclient")
        conn = oracledb.connect(
            user=settings.oracle_user,
            password=settings.oracle_password,
            dsn=settings.oracle_dsn,
            config_dir=settings.oracle_wallet_dir,
            wallet_location=settings.oracle_wallet_dir,
            wallet_password=settings.oracle_wallet_password,
        )
    else:
        # Modo thin — FreeSQL.com, Docker, ADB sin wallet
        conn = oracledb.connect(
            user=settings.oracle_user,
            password=settings.oracle_password,
            dsn=settings.oracle_dsn,
        )
    return conn

def init_db() -> None:
    """Crea las tablas si no existen (se llama al arrancar la API)."""
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS contenidos (
                    id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    titulo      VARCHAR2(500) NOT NULL,
                    texto       CLOB          NOT NULL,
                    idioma      VARCHAR2(10)  DEFAULT 'en' NOT NULL,
                    creado_en   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS categorias (
                    id      NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre  VARCHAR2(100) NOT NULL UNIQUE
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS clasificaciones (
                    id              NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    contenido_id    NUMBER(10) NOT NULL,
                    categoria_id    NUMBER(10) NOT NULL,
                    probabilidad    NUMBER(5,4) NOT NULL,
                    creado_en       TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    FOREIGN KEY (contenido_id) REFERENCES contenidos(id),
                    FOREIGN KEY (categoria_id) REFERENCES categorias(id)
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS terminos_clave (
                    id              NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    contenido_id    NUMBER(10)    NOT NULL,
                    palabra         VARCHAR2(200) NOT NULL,
                    peso_tfidf      NUMBER(8,6)   DEFAULT 0.0 NOT NULL,
                    FOREIGN KEY (contenido_id) REFERENCES contenidos(id) ON DELETE CASCADE
                )
            """)
            _crear_indice(cursor, "idx_clasif_creado", "clasificaciones", "creado_en DESC")
            _crear_indice(cursor, "idx_term_palabra", "terminos_clave", "palabra")
            _crear_indice(cursor, "idx_term_contenido", "terminos_clave", "contenido_id")
        conn.commit()

def _crear_indice(cursor: oracledb.Cursor, nombre: str, tabla: str, columnas: str) -> None:
    """Crea un índice si no existe (Oracle no tiene IF NOT EXISTS para índices)."""
    cursor.execute(
        "SELECT COUNT(*) FROM user_indexes WHERE index_name = :name",
        {"name": nombre.upper()},
    )
    if cursor.fetchone()[0] == 0:
        cursor.execute(f"CREATE INDEX {nombre} ON {tabla}({columnas})")


def guardar_clasificacion(
    titulo: str,
    texto: str,
    categoria: str,
    probabilidad: float,
    terminos_clave: list[dict],  # [{"palabra": "...", "peso": 0.xx}, ...]
    idioma: str = "en",
) -> int:
    """
    Guarda una clasificación completa en el schema normalizado.

    Returns
    -------
    int : ID de la clasificación creada.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            # 1. Categoría — INSERT si no existe
            cursor.execute(
                "SELECT id FROM categorias WHERE nombre = :nombre",
                {"nombre": categoria},
            )
            row = cursor.fetchone()
            if row:
                categoria_id = row[0]
            else:
                id_out = cursor.var(int)
                cursor.execute(
                    "INSERT INTO categorias (nombre) VALUES (:nombre) RETURNING id INTO :id_out",
                    {"nombre": categoria, "id_out": id_out},
                )
                categoria_id = id_out.getvalue()[0]

            # 2. Contenido
            contenido_id_out = cursor.var(int)
            cursor.execute(
                """
                INSERT INTO contenidos (titulo, texto, idioma)
                VALUES (:titulo, :texto, :idioma)
                RETURNING id INTO :id_out
                """,
                {"titulo": titulo, "texto": texto, "idioma": idioma, "id_out": contenido_id_out},
            )
            contenido_id = contenido_id_out.getvalue()[0]

            # 3. Clasificación
            clasificacion_id_out = cursor.var(int)
            cursor.execute(
                """
                INSERT INTO clasificaciones (contenido_id, categoria_id, probabilidad)
                VALUES (:contenido_id, :categoria_id, :probabilidad)
                RETURNING id INTO :id_out
                """,
                {
                    "contenido_id": contenido_id,
                    "categoria_id": categoria_id,
                    "probabilidad": probabilidad,
                    "id_out": clasificacion_id_out,
                },
            )
            clasificacion_id = clasificacion_id_out.getvalue()[0]

            # 4. Términos clave
            if terminos_clave:
                cursor.executemany(
                    """
                    INSERT INTO terminos_clave (contenido_id, palabra, peso_tfidf)
                    VALUES (:contenido_id, :palabra, :peso)
                    """,
                    [
                        {"contenido_id": contenido_id, "palabra": t["palabra"], "peso": t["peso"]}
                        for t in terminos_clave
                    ],
                )

        conn.commit()
        return clasificacion_id

def listar_contenidos(
    limite: int = 20,
    pagina: int = 1,
    categoria: str | None = None,
    q: str | None = None,
) -> tuple[list[dict[str, Any]], int]:
    """
    Busca y lista contenidos con filtros opcionales por palabra clave y categoría.

    Si no se pasa ``q``, actúa como el historial completo (solo paginado + filtro
    por categoría). Si se pasa ``q``, busca coincidencias en título, texto
    y términos clave (LIKE case-insensitive).

    Parameters
    ----------
    q : str | None
        Término de búsqueda (busca en título, texto y términos clave).
    categoria : str | None
        Filtro por nombre de categoría.
    limite : int
        Resultados por página (máx 100).
    pagina : int
        Número de página (desde 1).

    Returns
    -------
    tuple[list[dict], int]
        (items, total)
    """
    offset = (pagina - 1) * limite
    params: dict[str, Any] = {}
    conditions: list[str] = []

    # ── Condiciones dinámicas
    if q:
        q_clean = q.strip().lower()
        params["q"] = q_clean
        conditions.append(
            "(LOWER(c.titulo) LIKE '%' || :q || '%' OR "
            "LOWER(c.texto) LIKE '%' || :q || '%' OR "
            "EXISTS (SELECT 1 FROM terminos_clave tk "
            "         WHERE tk.contenido_id = c.id "
            "           AND LOWER(tk.palabra) LIKE '%' || :q || '%'))"
        )

    if categoria:
        params["categoria"] = categoria.strip().lower()
        conditions.append("LOWER(cat.nombre) = :categoria")

    where_clause = "WHERE " + " AND ".join(conditions) if conditions else ""

    with get_connection() as conn:
        with conn.cursor() as cursor:
            # ── Total
            cursor.execute(f"""
                SELECT COUNT(*) AS total
                FROM contenidos c
                JOIN clasificaciones cl ON cl.contenido_id = c.id
                JOIN categorias cat ON cl.categoria_id = cat.id
                {where_clause}
            """, params)
            total = cursor.fetchone()[0]

            if total == 0:
                return [], 0

            # ── Página
            cursor.execute(f"""
                SELECT
                    c.id AS contenido_id, c.titulo, c.texto, c.idioma,
                    cl.id AS clasificacion_id, cl.probabilidad, cl.creado_en,
                    cat.nombre AS categoria
                FROM contenidos c
                JOIN clasificaciones cl ON cl.contenido_id = c.id
                JOIN categorias cat ON cl.categoria_id = cat.id
                {where_clause}
                ORDER BY cl.creado_en DESC
                OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
            """, {**params, "offset": offset, "limit": limite})

            rows = cursor.fetchall()

            items: list[dict[str, Any]] = []
            contenido_ids: list[int] = []

            for row in rows:
                contenido_id = row[0]
                contenido_ids.append(contenido_id)

                # Leer CLOB o string (truncado a 200 caracteres)
                texto_raw = row[2]
                texto = texto_raw.read()[:200] if hasattr(texto_raw, "read") else str(texto_raw)[:200]

                items.append({
                    "id": contenido_id,
                    "titulo": row[1],
                    "texto": texto,
                    "categoria": row[7],
                    "probabilidad": row[5],
                    "idioma": row[3],
                    "creado_en": _fmt_dt(row[6]),
                    "informacion_adicional": [],
                })

            # ── Batch fetch de términos clave
            if contenido_ids:
                placeholders = ", ".join(f":id{i}" for i in range(len(contenido_ids)))
                cursor.execute(f"""
                    SELECT contenido_id, palabra
                    FROM terminos_clave
                    WHERE contenido_id IN ({placeholders})
                    ORDER BY contenido_id, peso_tfidf DESC
                """, {f"id{i}": cid for i, cid in enumerate(contenido_ids)})

                term_map = defaultdict(list)
                for cid, palabra in cursor.fetchall():
                    term_map[cid].append(palabra)

                for item in items:
                    item["informacion_adicional"] = term_map.get(item["id"], [])

    return items, total

def _fmt_dt(val: Any) -> str:
    """Convierte datetime/timestamp de Oracle a string ISO."""
    if hasattr(val, "isoformat"):
        return val.isoformat()
    return str(val)

def obtener_terminos_por_contenido(contenido_id: int) -> list[dict]:
    """Devuelve los términos clave de un contenido."""
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                "SELECT palabra, peso_tfidf FROM terminos_clave WHERE contenido_id = :cid ORDER BY peso_tfidf DESC",
                {"cid": contenido_id},
            )
            return [
                {"palabra": row[0], "peso": row[1]}
                for row in cursor.fetchall()
            ]

def obtener_detalle_clasificacion(clasificacion_id: int) -> dict | None:
    """Devuelve una clasificación completa con contenido, categoría y términos."""
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    c.id            AS contenido_id,
                    c.titulo,
                    c.texto,
                    c.idioma,
                    cl.id           AS clasificacion_id,
                    cl.probabilidad,
                    cl.creado_en,
                    cat.nombre      AS categoria
                FROM clasificaciones cl
                JOIN contenidos c   ON cl.contenido_id = c.id
                JOIN categorias cat ON cl.categoria_id = cat.id
                WHERE cl.id = :cid
                """,
                {"cid": clasificacion_id},
            )
            row = cursor.fetchone()
            if not row:
                return None

            return {
                "contenido_id": row[0],
                "titulo": row[1],
                "texto": row[2],
                "idioma": row[3],
                "clasificacion_id": row[4],
                "probabilidad": row[5],
                "creado_en": _fmt_dt(row[6]),
                "categoria": row[7],
                "terminos": obtener_terminos_por_contenido(row[0]),
            }

def buscar_contenidos_por_palabra(
    palabra: str,
    limite: int = 20,
    pagina: int = 1,
) -> tuple[list[dict], int]:
    """
    Busca contenidos que contengan una palabra clave.

    Usa terminos_clave para encontrar contenido_id.
    Ordenado por peso_tfidf descendente.
    """
    offset = (pagina - 1) * limite

    with get_connection() as conn:
        with conn.cursor() as cursor:
            # Total
            cursor.execute(
                """
                SELECT COUNT(DISTINCT c.id) AS total
                FROM contenidos c
                JOIN terminos_clave t ON c.id = t.contenido_id
                WHERE t.palabra = :palabra
                """,
                {"palabra": palabra},
            )
            total = cursor.fetchone()[0]

            # Página
            cursor.execute(
                """
                SELECT DISTINCT
                    c.id            AS contenido_id,
                    c.titulo,
                    c.texto,
                    c.idioma,
                    cl.id           AS clasificacion_id,
                    cl.probabilidad,
                    cl.creado_en,
                    cat.nombre      AS categoria,
                    t.peso_tfidf
                FROM contenidos c
                JOIN terminos_clave t       ON c.id = t.contenido_id
                JOIN clasificaciones cl     ON c.id = cl.contenido_id
                JOIN categorias cat         ON cl.categoria_id = cat.id
                WHERE t.palabra = :palabra
                ORDER BY t.peso_tfidf DESC
                OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
                """,
                {"palabra": palabra, "offset": offset, "limit": limite},
            )
            rows = cursor.fetchall()

    items = []
    for row in rows:
        items.append({
            "contenido_id": row[0],
            "clasificacion_id": row[4],
            "titulo": row[1],
            "texto": row[2][:200],
            "categoria": row[7],
            "probabilidad": row[5],
            "idioma": row[3],
            "creado_en": _fmt_dt(row[6]),
            "relevancia": row[8],
        })

    return items, total

def listar_categorias() -> list[str]:
    """Devuelve todas las categorías disponibles."""
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("SELECT nombre FROM categorias ORDER BY nombre")
            return [row[0] for row in cursor.fetchall()]


def obtener_contenido_por_id(contenido_id: int) -> dict | None:
    """
    Devuelve el detalle completo de un contenido por su ID.

    Incluye texto completo (sin truncar), categoría, términos clave, etc.
    Returns ``None`` si no existe.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    c.id            AS contenido_id,
                    c.titulo,
                    c.texto,
                    c.idioma,
                    cl.id           AS clasificacion_id,
                    cl.probabilidad,
                    cl.creado_en,
                    cat.nombre      AS categoria
                FROM contenidos c
                JOIN clasificaciones cl ON cl.contenido_id = c.id
                JOIN categorias cat    ON cl.categoria_id = cat.id
                WHERE c.id = :cid
            """, {"cid": contenido_id})
            row = cursor.fetchone()
            if not row:
                return None

            # Leer CLOB
            texto_raw = row[2]
            texto = texto_raw.read() if hasattr(texto_raw, "read") else str(texto_raw)

            item = {
                "id": row[0],
                "titulo": row[1],
                "texto": texto,
                "categoria": row[7],
                "probabilidad": row[5],
                "idioma": row[3],
                "creado_en": _fmt_dt(row[6]),
                "informacion_adicional": [],
            }

            # Términos clave
            cursor.execute("""
                SELECT palabra
                FROM terminos_clave
                WHERE contenido_id = :cid
                ORDER BY peso_tfidf DESC
            """, {"cid": contenido_id})
            item["informacion_adicional"] = [r[0] for r in cursor.fetchall()]

            return item
