"""
Persistencia en Oracle Database.

Schema normalizado: contenidos → clasificaciones → categorias + terminos_clave.
Driver: python-oracledb (thin mode siempre — soporta wallets mTLS nativamente).
Thick mode (Oracle Instant Client) habilitable solo si se necesita.
Funciona con FreeSQL.com, Docker, y OCI Autonomous Database.
"""

from collections import defaultdict
from datetime import datetime, timezone
from typing import Any
import array

import oracledb

from .config import settings


def get_connection() -> oracledb.Connection:
    """Devuelve una conexión a Oracle Database.

    - Si hay wallet configurada → thin mode con wallet mTLS
    - Si no → thin mode directo (FreeSQL.com, Docker, ADB sin wallet)
    """
    if settings.oracle_wallet_dir:
        # Modo thin con wallet mTLS (no requiere Oracle Instant Client).
        # python-oracledb 2.0+ soporta wallets en thin mode de forma nativa.
        # TODO: si en el futuro se necesita thick mode (pools heterogéneos,
        #       NNE, Kerberos, SODA), agregar acá:
        #   oracledb.init_oracle_client(lib_dir=r"ruta\al\instantclient")
        conn = oracledb.connect(
            user=settings.oracle_user,
            password=settings.oracle_password,
            dsn=settings.oracle_dsn,
            config_dir=settings.oracle_wallet_dir,
            wallet_location=settings.oracle_wallet_dir,
            wallet_password=settings.oracle_wallet_password,
        )
    else:
        # Modo thin — FreeSQL.com, Docker, ADB sin wallet
        conn = oracledb.connect(
            user=settings.oracle_user,
            password=settings.oracle_password,
            dsn=settings.oracle_dsn,
        )
    return conn

def init_db() -> None:
    """Crea las tablas si no existen (se llama al arrancar la API)."""
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS contenidos (
                    id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    titulo      VARCHAR2(500) NOT NULL,
                    texto       CLOB          NOT NULL,
                    idioma      VARCHAR2(10)  DEFAULT 'en' NOT NULL,
                    creado_en   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS categorias (
                    id      NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre  VARCHAR2(100) NOT NULL UNIQUE
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS clasificaciones (
                    id              NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    contenido_id    NUMBER(10) NOT NULL,
                    categoria_id    NUMBER(10) NOT NULL,
                    probabilidad    NUMBER(5,4) NOT NULL,
                    creado_en       TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    FOREIGN KEY (contenido_id) REFERENCES contenidos(id) ON DELETE CASCADE,
                    FOREIGN KEY (categoria_id) REFERENCES categorias(id)
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS terminos_clave (
                    id              NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    contenido_id    NUMBER(10)    NOT NULL,
                    palabra         VARCHAR2(200) NOT NULL,
                    peso_tfidf      NUMBER(8,6)   DEFAULT 0.0 NOT NULL,
                    FOREIGN KEY (contenido_id) REFERENCES contenidos(id) ON DELETE CASCADE
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS feedback_clasificacion (
                    id                      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    contenido_id            NUMBER(10) NOT NULL,
                    categoria_original_id   NUMBER(10) NOT NULL,
                    categoria_corregida_id  NUMBER(10) NOT NULL,
                    usuario                 VARCHAR2(100),
                    motivo                  VARCHAR2(500),
                    creado_en               TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    FOREIGN KEY (contenido_id)          REFERENCES contenidos(id) ON DELETE CASCADE,
                    FOREIGN KEY (categoria_original_id) REFERENCES categorias(id),
                    FOREIGN KEY (categoria_corregida_id) REFERENCES categorias(id)
                )
            """)
            _crear_indice(cursor, "idx_clasif_creado", "clasificaciones", "creado_en DESC")
            _crear_indice(cursor, "idx_term_palabra", "terminos_clave", "palabra")
            _crear_indice(cursor, "idx_term_contenido", "terminos_clave", "contenido_id")
            _crear_indice(cursor, "idx_feedback_contenido", "feedback_clasificacion", "contenido_id")
            # Una clasificación vigente por contenido (evita duplicados)
            _crear_indice_unico(cursor, "uq_clasif_contenido", "clasificaciones", "contenido_id")

            # Búsqueda semántica: columna de embeddings (Oracle 23ai+/VECTOR nativo)
            _migrar_columna_embedding(cursor)
        conn.commit()


def _migrar_columna_embedding(cursor: oracledb.Cursor) -> None:
    """Agrega la columna ``embedding`` a ``contenidos`` si no existe.

    Oracle no tiene ``ALTER TABLE ... ADD COLUMN IF NOT EXISTS``, así que
    se verifica primero contra ``user_tab_columns`` (mismo patrón que
    ``_crear_indice`` usa con ``user_indexes``).

    Requiere Oracle Database 23ai o superior (tipo ``VECTOR`` nativo).
    """
    cursor.execute(
        """
        SELECT COUNT(*) FROM user_tab_columns
        WHERE table_name = 'CONTENIDOS' AND column_name = 'EMBEDDING'
        """
    )
    if cursor.fetchone()[0] > 0:
        return

    cursor.execute(
        "ALTER TABLE contenidos ADD (embedding VECTOR(384, FLOAT32))"
    )

def _crear_indice(cursor: oracledb.Cursor, nombre: str, tabla: str, columnas: str) -> None:
    """Crea un índice si no existe (Oracle no tiene IF NOT EXISTS para índices)."""
    cursor.execute(
        "SELECT COUNT(*) FROM user_indexes WHERE index_name = :name",
        {"name": nombre.upper()},
    )
    if cursor.fetchone()[0] == 0:
        cursor.execute(f"CREATE INDEX {nombre} ON {tabla}({columnas})")


def _crear_indice_unico(cursor: oracledb.Cursor, nombre: str, tabla: str, columnas: str) -> None:
    """Crea un índice UNIQUE si no existe y no hay duplicados previos.

    Si ya hay filas duplicadas (por ejemplo en una BD con datos históricos),
    se omite el índice para no romper ``init_db()``; la limpieza y creación
    quedan como tarea manual (ver mensaje al final del flujo).
    """
    cursor.execute(
        "SELECT COUNT(*) FROM user_indexes WHERE index_name = :name",
        {"name": nombre.upper()},
    )
    if cursor.fetchone()[0] > 0:
        return

    cursor.execute(
        f"SELECT COUNT(*) FROM ("
        f"SELECT {columnas} FROM {tabla} GROUP BY {columnas} HAVING COUNT(*) > 1)"
    )
    if cursor.fetchone()[0] > 0:
        return

    cursor.execute(f"CREATE UNIQUE INDEX {nombre} ON {tabla}({columnas})")


def guardar_clasificacion(
    titulo: str,
    texto: str,
    categoria: str,
    probabilidad: float,
    terminos_clave: list[dict],  # [{"palabra": "...", "peso": 0.xx}, ...]
    idioma: str = "en",
    embedding: list[float] | None = None,
) -> int:
    """
    Guarda una clasificación completa en el schema normalizado.

    Parameters
    ----------
    embedding : list[float] | None
        Vector de embedding (384 dims) para búsqueda semántica. Si es
        ``None``, la fila queda sin embedding y no aparece en resultados
        de ``/contenidos/busqueda-semantica`` hasta que se recalcule.

    Returns
    -------
    int : ID del CONTENIDO creado (``contenidos.id``). Es el ID que expone
    la API en GET /contenidos y GET /contenido/{id}, por eso se devuelve
    este y no el de ``clasificaciones.id`` (secuencias independientes).
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            # 1. Categoría — INSERT si no existe
            cursor.execute(
                "SELECT id FROM categorias WHERE nombre = :nombre",
                {"nombre": categoria},
            )
            row = cursor.fetchone()
            if row:
                categoria_id = row[0]
            else:
                id_out = cursor.var(int)
                cursor.execute(
                    "INSERT INTO categorias (nombre) VALUES (:nombre) RETURNING id INTO :id_out",
                    {"nombre": categoria, "id_out": id_out},
                )
                categoria_id = id_out.getvalue()[0]

            # 2. Contenido
            contenido_id_out = cursor.var(int)
            cursor.execute(
                """
                INSERT INTO contenidos (titulo, texto, idioma, embedding)
                VALUES (:titulo, :texto, :idioma, :embedding)
                RETURNING id INTO :id_out
                """,
                {
                    "titulo": titulo,
                    "texto": texto,
                    "idioma": idioma,
                    "embedding": array.array("f", embedding) if embedding else None,
                    "id_out": contenido_id_out,
                },
            )
            contenido_id = contenido_id_out.getvalue()[0]

            # 3. Clasificación
            cursor.execute(
                """
                INSERT INTO clasificaciones (contenido_id, categoria_id, probabilidad)
                VALUES (:contenido_id, :categoria_id, :probabilidad)
                """,
                {
                    "contenido_id": contenido_id,
                    "categoria_id": categoria_id,
                    "probabilidad": probabilidad,
                },
            )

            # 4. Términos clave
            if terminos_clave:
                cursor.executemany(
                    """
                    INSERT INTO terminos_clave (contenido_id, palabra, peso_tfidf)
                    VALUES (:contenido_id, :palabra, :peso)
                    """,
                    [
                        {"contenido_id": contenido_id, "palabra": t["palabra"], "peso": t["peso"]}
                        for t in terminos_clave
                    ],
                )

        conn.commit()
        return contenido_id


def existe_contenido_duplicado(titulo: str, texto: str) -> bool:
    """Indica si ya existe un contenido con el mismo título y texto.

    Compara sin distinguir mayúsculas/minúsculas ni espacios extra, porque el
    validador ya normaliza (NFC + strip) antes de llegar acá. El objetivo es
    evitar registros duplicados como los reportados en el testing (el mismo
    título+texto se registró dos veces con IDs distintos).
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM contenidos
                WHERE UPPER(TRIM(titulo)) = UPPER(TRIM(:titulo))
                  AND UPPER(TRIM(texto)) = UPPER(TRIM(:texto))
                """,
                {"titulo": titulo, "texto": texto},
            )
            return cursor.fetchone()[0] > 0

def listar_contenidos(
    limite: int = 20,
    pagina: int = 1,
    categoria: str | None = None,
    q: str | None = None,
) -> tuple[list[dict[str, Any]], int]:
    """
    Busca y lista contenidos con filtros opcionales por palabra clave y categoría.

    Si no se pasa ``q``, actúa como el historial completo (solo paginado + filtro
    por categoría). Si se pasa ``q``, busca coincidencias en título, texto
    y términos clave (LIKE case-insensitive).

    Parameters
    ----------
    q : str | None
        Término de búsqueda (busca en título, texto y términos clave).
    categoria : str | None
        Filtro por nombre de categoría.
    limite : int
        Resultados por página (máx 100).
    pagina : int
        Número de página (desde 1).

    Returns
    -------
    tuple[list[dict], int]
        (items, total)
    """
    offset = (pagina - 1) * limite
    params: dict[str, Any] = {}
    conditions: list[str] = []

    # ── Condiciones dinámicas
    if q:
        q_clean = q.strip().lower()
        params["q"] = q_clean
        conditions.append(
            "(LOWER(c.titulo) LIKE '%' || :q || '%' OR "
            "LOWER(c.texto) LIKE '%' || :q || '%' OR "
            "EXISTS (SELECT 1 FROM terminos_clave tk "
            "         WHERE tk.contenido_id = c.id "
            "           AND LOWER(tk.palabra) LIKE '%' || :q || '%'))"
        )

    if categoria:
        params["categoria"] = categoria.strip().lower()
        conditions.append("LOWER(cat.nombre) = :categoria")

    where_clause = "WHERE " + " AND ".join(conditions) if conditions else ""

    with get_connection() as conn:
        with conn.cursor() as cursor:
            # ── Total
            cursor.execute(f"""
                SELECT COUNT(*) AS total
                FROM contenidos c
                JOIN clasificaciones cl ON cl.contenido_id = c.id
                JOIN categorias cat ON cl.categoria_id = cat.id
                {where_clause}
            """, params)
            total = cursor.fetchone()[0]

            if total == 0:
                return [], 0

            # ── Página
            cursor.execute(f"""
                SELECT
                    c.id AS contenido_id, c.titulo, c.texto, c.idioma,
                    cl.id AS clasificacion_id, cl.probabilidad, cl.creado_en,
                    cat.nombre AS categoria
                FROM contenidos c
                JOIN clasificaciones cl ON cl.contenido_id = c.id
                JOIN categorias cat ON cl.categoria_id = cat.id
                {where_clause}
                ORDER BY cl.creado_en DESC
                OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
            """, {**params, "offset": offset, "limit": limite})

            rows = cursor.fetchall()

            items: list[dict[str, Any]] = []
            contenido_ids: list[int] = []

            for row in rows:
                contenido_id = row[0]
                contenido_ids.append(contenido_id)

                # Leer CLOB o string (truncado a 200 caracteres)
                texto_raw = row[2]
                texto = texto_raw.read()[:200] if hasattr(texto_raw, "read") else str(texto_raw)[:200]

                items.append({
                    "id": contenido_id,
                    "titulo": row[1],
                    "texto": texto,
                    "categoria": row[7],
                    "probabilidad": row[5],
                    "idioma": row[3],
                    "creado_en": _fmt_dt(row[6]),
                    "informacion_adicional": [],
                })

            # ── Batch fetch de términos clave
            if contenido_ids:
                placeholders = ", ".join(f":id{i}" for i in range(len(contenido_ids)))
                cursor.execute(f"""
                    SELECT contenido_id, palabra
                    FROM terminos_clave
                    WHERE contenido_id IN ({placeholders})
                    ORDER BY contenido_id, peso_tfidf DESC
                """, {f"id{i}": cid for i, cid in enumerate(contenido_ids)})

                term_map = defaultdict(list)
                for cid, palabra in cursor.fetchall():
                    term_map[cid].append(palabra)

                for item in items:
                    item["informacion_adicional"] = term_map.get(item["id"], [])

    return items, total

def _fmt_dt(val: Any) -> str:
    """Convierte datetime/timestamp de Oracle a string ISO."""
    if hasattr(val, "isoformat"):
        return val.isoformat()
    return str(val)

def obtener_terminos_por_contenido(contenido_id: int) -> list[dict]:
    """Devuelve los términos clave de un contenido."""
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                "SELECT palabra, peso_tfidf FROM terminos_clave WHERE contenido_id = :cid ORDER BY peso_tfidf DESC",
                {"cid": contenido_id},
            )
            return [
                {"palabra": row[0], "peso": row[1]}
                for row in cursor.fetchall()
            ]

def obtener_detalle_clasificacion(clasificacion_id: int) -> dict | None:
    """Devuelve una clasificación completa con contenido, categoría y términos."""
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    c.id            AS contenido_id,
                    c.titulo,
                    c.texto,
                    c.idioma,
                    cl.id           AS clasificacion_id,
                    cl.probabilidad,
                    cl.creado_en,
                    cat.nombre      AS categoria
                FROM clasificaciones cl
                JOIN contenidos c   ON cl.contenido_id = c.id
                JOIN categorias cat ON cl.categoria_id = cat.id
                WHERE cl.id = :cid
                """,
                {"cid": clasificacion_id},
            )
            row = cursor.fetchone()
            if not row:
                return None

            return {
                "contenido_id": row[0],
                "titulo": row[1],
                "texto": row[2],
                "idioma": row[3],
                "clasificacion_id": row[4],
                "probabilidad": row[5],
                "creado_en": _fmt_dt(row[6]),
                "categoria": row[7],
                "terminos": obtener_terminos_por_contenido(row[0]),
            }

def buscar_contenidos_por_palabra(
    palabra: str,
    limite: int = 20,
    pagina: int = 1,
) -> tuple[list[dict], int]:
    """
    Busca contenidos que contengan una palabra clave.

    Usa terminos_clave para encontrar contenido_id.
    Ordenado por peso_tfidf descendente.
    """
    offset = (pagina - 1) * limite

    with get_connection() as conn:
        with conn.cursor() as cursor:
            # Total
            cursor.execute(
                """
                SELECT COUNT(DISTINCT c.id) AS total
                FROM contenidos c
                JOIN terminos_clave t ON c.id = t.contenido_id
                WHERE t.palabra = :palabra
                """,
                {"palabra": palabra},
            )
            total = cursor.fetchone()[0]

            # Página
            cursor.execute(
                """
                SELECT DISTINCT
                    c.id            AS contenido_id,
                    c.titulo,
                    c.texto,
                    c.idioma,
                    cl.id           AS clasificacion_id,
                    cl.probabilidad,
                    cl.creado_en,
                    cat.nombre      AS categoria,
                    t.peso_tfidf
                FROM contenidos c
                JOIN terminos_clave t       ON c.id = t.contenido_id
                JOIN clasificaciones cl     ON c.id = cl.contenido_id
                JOIN categorias cat         ON cl.categoria_id = cat.id
                WHERE t.palabra = :palabra
                ORDER BY t.peso_tfidf DESC
                OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
                """,
                {"palabra": palabra, "offset": offset, "limit": limite},
            )
            rows = cursor.fetchall()

    items = []
    for row in rows:
        items.append({
            "contenido_id": row[0],
            "clasificacion_id": row[4],
            "titulo": row[1],
            "texto": row[2][:200],
            "categoria": row[7],
            "probabilidad": row[5],
            "idioma": row[3],
            "creado_en": _fmt_dt(row[6]),
            "relevancia": row[8],
        })

    return items, total


def buscar_por_similitud(
    embedding: list[float],
    top_n: int = 5,
    categoria: str | None = None,
) -> list[dict]:
    """
    Busca los contenidos semánticamente más parecidos a ``embedding``.

    Usa ``VECTOR_DISTANCE(..., COSINE)`` nativo de Oracle (23ai+): la
    distancia coseno va de 0 (idéntico) a 2 (opuesto), así que se convierte
    a similitud con ``1 - distancia`` para que sea consistente con
    ``calcular_similitud_coseno`` si en algún momento se agrega un fallback
    en Python.

    No requiere traer todos los embeddings a memoria — la BD hace el
    cálculo y el ordenamiento; solo bajan las ``top_n`` filas finales.
    Sin índice vectorial esto es un escaneo completo de la tabla
    (fuerza bruta), aceptable para el volumen de un hackathon. Si el
    volumen de datos crece, agregar un ``CREATE VECTOR INDEX`` sobre
    ``contenidos.embedding`` con ``DISTANCE COSINE``.

    Contenidos sin embedding (``embedding IS NULL``, p. ej. si se guardaron
    antes de esta migración) quedan afuera automáticamente.

    Parameters
    ----------
    embedding : list[float]
        Vector de la consulta (mismas dimensiones que la columna, 384).
    top_n : int
        Cantidad máxima de resultados.
    categoria : str | None
        Filtro opcional por nombre de categoría.

    Returns
    -------
    list[dict] : cada item con ``id``, ``titulo``, ``categoria``,
    ``informacion_adicional``, ``idioma``, ``creado_en``, ``similitud``.
    """
    condiciones = ["c.embedding IS NOT NULL"]
    params: dict[str, Any] = {
        "query_vec": array.array("f", embedding),
        "top_n": top_n,
    }

    if categoria:
        condiciones.append("cat.nombre = :categoria")
        params["categoria"] = categoria

    where_clause = " AND ".join(condiciones)

    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                f"""
                SELECT
                    c.id,
                    c.titulo,
                    cat.nombre AS categoria,
                    c.idioma,
                    c.creado_en,
                    VECTOR_DISTANCE(c.embedding, :query_vec, COSINE) AS distancia
                FROM contenidos c
                JOIN clasificaciones cl ON c.id = cl.contenido_id
                JOIN categorias cat    ON cl.categoria_id = cat.id
                WHERE {where_clause}
                ORDER BY distancia ASC
                FETCH FIRST :top_n ROWS ONLY
                """,
                params,
            )
            rows = cursor.fetchall()

    resultados = []
    for row in rows:
        contenido_id = row[0]
        resultados.append({
    "id": contenido_id,
    "titulo": row[1],
    "categoria": row[2],
    "idioma": row[3],
    "creado_en": _fmt_dt(row[4]),
    "similitud": round(1.0 - float(row[5]), 4),
    "informacion_adicional": [
        t["palabra"] for t in obtener_terminos_por_contenido(contenido_id)
    ],
})
    return resultados


def listar_categorias() -> list[dict]:
    """Devuelve todas las categorías con su ``id`` y ``nombre``."""
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("SELECT id, nombre FROM categorias ORDER BY nombre")
            return [{"id": row[0], "nombre": row[1]} for row in cursor.fetchall()]


def obtener_contenido_por_id(contenido_id: int) -> dict | None:
    """
    Devuelve el detalle completo de un contenido por su ID.

    Incluye texto completo (sin truncar), categoría, términos clave, etc.
    Returns ``None`` si no existe.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    c.id            AS contenido_id,
                    c.titulo,
                    c.texto,
                    c.idioma,
                    cl.id           AS clasificacion_id,
                    cl.probabilidad,
                    cl.creado_en,
                    cat.nombre      AS categoria
                FROM contenidos c
                JOIN clasificaciones cl ON cl.contenido_id = c.id
                JOIN categorias cat    ON cl.categoria_id = cat.id
                WHERE c.id = :cid
            """, {"cid": contenido_id})
            row = cursor.fetchone()
            if not row:
                return None

            # Leer CLOB
            texto_raw = row[2]
            texto = texto_raw.read() if hasattr(texto_raw, "read") else str(texto_raw)

            item = {
                "id": row[0],
                "titulo": row[1],
                "texto": texto,
                "categoria": row[7],
                "probabilidad": row[5],
                "idioma": row[3],
                "creado_en": _fmt_dt(row[6]),
                "informacion_adicional": [],
            }

            # Términos clave
            cursor.execute("""
                SELECT palabra
                FROM terminos_clave
                WHERE contenido_id = :cid
                ORDER BY peso_tfidf DESC
            """, {"cid": contenido_id})
            item["informacion_adicional"] = [r[0] for r in cursor.fetchall()]

            return item


def eliminar_contenido(contenido_id: int) -> bool:
    """
    Elimina un contenido y sus registros relacionados.

    Con ``ON DELETE CASCADE`` en ``clasificaciones`` y ``terminos_clave``,
    un solo ``DELETE FROM contenidos`` alcanza: Oracle se encarga del resto.

    Returns ``True`` si existía, ``False`` si no.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("SELECT id FROM contenidos WHERE id = :cid", {"cid": contenido_id})
            if not cursor.fetchone():
                return False

            cursor.execute("DELETE FROM contenidos WHERE id = :cid", {"cid": contenido_id})
            conn.commit()
            return True


def actualizar_contenido_db(
    contenido_id: int,
    titulo: str,
    texto: str,
    idioma: str,
    categoria: str,
    probabilidad: float,
    terminos_clave: list[dict],
    embedding:list[float] = None,
) -> dict | None:
    """
    Actualiza un contenido existente y su clasificación.

    1. UPDATE ``contenidos`` (titulo, texto, idioma)
    2. DELETE ``terminos_clave`` + ``clasificaciones`` viejos
    3. INSERT nueva ``clasificacion`` y nuevos ``terminos_clave``

    Returns el dict completo del contenido actualizado, o ``None`` si no existe.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            # Verificar que exista
            cursor.execute("SELECT id FROM contenidos WHERE id = :cid", {"cid": contenido_id})
            if not cursor.fetchone():
                return None

          # 1. Actualizar contenido (incluyendo el embedding si existe)

            if embedding is not None:

                vector = array.array("f", embedding)

                cursor.execute(
                    """
                    UPDATE contenidos
                    SET
                        titulo = :titulo,
                        texto = :texto,
                        idioma = :idioma,
                        embedding = :embedding
                    WHERE id = :cid
                    """,
                    {
                        "titulo": titulo,
                        "texto": texto,
                        "idioma": idioma,
                        "embedding": vector,
                        "cid": contenido_id,
                    },
                )

            else:

                cursor.execute(
                    """
                    UPDATE contenidos
                    SET
                        titulo = :titulo,
                        texto = :texto,
                        idioma = :idioma
                    WHERE id = :cid
                    """,
                    {
                        "titulo": titulo,
                        "texto": texto,
                        "idioma": idioma,
                        "cid": contenido_id,
                    },
                )

            # 2. Eliminar datos de clasificación anteriores
            cursor.execute(
                "DELETE FROM terminos_clave WHERE contenido_id = :cid",
                {"cid": contenido_id},
            )
            cursor.execute(
                "DELETE FROM clasificaciones WHERE contenido_id = :cid",
                {"cid": contenido_id},
            )

            # 3. Categoría — obtener o crear
            cursor.execute(
                "SELECT id FROM categorias WHERE nombre = :nombre",
                {"nombre": categoria},
            )
            row = cursor.fetchone()
            if row:
                categoria_id = row[0]
            else:
                id_out = cursor.var(int)
                cursor.execute(
                    "INSERT INTO categorias (nombre) VALUES (:nombre) RETURNING id INTO :id_out",
                    {"nombre": categoria, "id_out": id_out},
                )
                categoria_id = id_out.getvalue()[0]

            # 4. Nueva clasificación
            cursor.execute(
                """
                INSERT INTO clasificaciones (contenido_id, categoria_id, probabilidad)
                VALUES (:cid, :cat_id, :prob)
                """,
                {"cid": contenido_id, "cat_id": categoria_id, "prob": probabilidad},
            )

            # 5. Nuevos términos clave
            if terminos_clave:
                cursor.executemany(
                    """
                    INSERT INTO terminos_clave (contenido_id, palabra, peso_tfidf)
                    VALUES (:cid, :palabra, :peso)
                    """,
                    [
                        {"cid": contenido_id, "palabra": t["palabra"], "peso": t["peso"]}
                        for t in terminos_clave
                    ],
                )

            conn.commit()

    return obtener_contenido_por_id(contenido_id)


def corregir_clasificacion(
    contenido_id: int,
    nueva_categoria_id: int,
    usuario: str | None = None,
    motivo: str | None = None,
) -> dict | None:
    """
    Corrige o confirma manualmente la clasificación de un contenido.

    1. Lee la clasificación vigente del contenido.
    2. Valida que ``nueva_categoria_id`` exista en ``categorias``.
    3. Si la categoría cambió, actualiza ``clasificaciones`` con
       ``probabilidad = 1.0`` (una corrección humana es verdad de terreno).
    4. Registra el par (original → corregida) en ``feedback_clasificacion``,
       que sirve como dataset para mejorar el modelo.

    Returns
    -------
    dict | None
        Resumen con ``categoria_anterior``, ``categoria_nueva``, ``corregida``
        y el resto del feedback. ``None`` si el contenido no existe.
        ``ValueError`` si la categoría destino no existe.
    """
    with get_connection() as conn:
        with conn.cursor() as cursor:
            # 1. Clasificación vigente del contenido
            cursor.execute("""
                SELECT cl.categoria_id, cat.nombre
                FROM clasificaciones cl
                JOIN categorias cat ON cl.categoria_id = cat.id
                WHERE cl.contenido_id = :cid
            """, {"cid": contenido_id})
            row = cursor.fetchone()
            if not row:
                return None
            categoria_anterior_id, categoria_anterior = row[0], row[1]

            # 2. Validar que la categoría destino exista
            cursor.execute(
                "SELECT nombre FROM categorias WHERE id = :cat_id",
                {"cat_id": nueva_categoria_id},
            )
            cat_row = cursor.fetchone()
            if not cat_row:
                raise ValueError(f"La categoría con id {nueva_categoria_id} no existe")
            categoria_nueva = cat_row[0]

            corregida = categoria_anterior_id != nueva_categoria_id

            # 3. Si cambió, actualizar la clasificación vigente
            if corregida:
                cursor.execute("""
                    UPDATE clasificaciones
                    SET categoria_id = :cat_id, probabilidad = 1.0
                    WHERE contenido_id = :cid
                """, {"cat_id": nueva_categoria_id, "cid": contenido_id})

            # 4. Registrar el feedback (par original → corregida)
            cursor.execute("""
                INSERT INTO feedback_clasificacion
                    (contenido_id, categoria_original_id, categoria_corregida_id, usuario, motivo)
                VALUES (:cid, :orig, :nueva, :usuario, :motivo)
            """, {
                "cid": contenido_id,
                "orig": categoria_anterior_id,
                "nueva": nueva_categoria_id,
                "usuario": usuario,
                "motivo": motivo,
            })

            conn.commit()

            return {
                "contenido_id": contenido_id,
                "categoria_anterior": categoria_anterior,
                "categoria_nueva": categoria_nueva,
                "corregida": corregida,
                "usuario": usuario,
                "motivo": motivo,
                "creado_en": datetime.now(timezone.utc).isoformat(),
            }

def exportar_dataset(
    idioma: str = "todos",
    solo_verificados: bool = True,
) -> list[dict]:
    """
    Exporta contenidos clasificados como dataset de entrenamiento.

    Devuelve filas con ``titulo``, ``texto`` y ``categoria`` (la vigente,
    es decir la última corrección humana si la hubo).

    Parameters
    ----------
    idioma : "en" | "es" | "todos"
        Filtra por idioma del contenido. Con ``todos`` no filtra.
    solo_verificados : bool
        ``True`` → solo contenidos con feedback humano (ground truth puro).
        ``False`` → todos, usando la categoría vigente (los no verificados
        quedan con la predicción del modelo, pseudo-etiquetas).

    Returns
    -------
    list[dict]
        Lista de filas ``{"titulo", "texto", "categoria"}``.
    """
    conditions: list[str] = []
    params: dict[str, Any] = {}

    if idioma in ("en", "es"):
        params["idioma"] = idioma
        conditions.append("c.idioma = :idioma")

    if solo_verificados:
        conditions.append(
            "EXISTS (SELECT 1 FROM feedback_clasificacion f "
            "WHERE f.contenido_id = c.id)"
        )

    where_clause = "WHERE " + " AND ".join(conditions) if conditions else ""

    items: list[dict] = []
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(f"""
                SELECT c.titulo, c.texto, cat.nombre AS categoria
                FROM contenidos c
                JOIN clasificaciones cl ON cl.contenido_id = c.id
                JOIN categorias cat ON cl.categoria_id = cat.id
                {where_clause}
                ORDER BY c.id
            """, params)

            # Leer los CLOB DENTRO de la conexión: oracledb los resuelve de forma
            # perezosa y hace .read() con la conexión ya cerrada tira
            # DPY-1001 (not connected to database).
            for titulo, texto_raw, categoria in cursor:
                texto = texto_raw.read() if hasattr(texto_raw, "read") else str(texto_raw)
                items.append({"titulo": titulo, "texto": texto, "categoria": categoria})

    return items