# k8s/1-config/oracle-wallet-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: oracle-wallet
type: Opaque
data:
  cwallet.sso: <contenido_base64>
  ewallet.p12: <contenido_base64>
  tnsnames.ora: <contenido_base64>
